# Generated by Django 2.0.3 on 2018-03-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closeness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('leader', models.IntegerField(choices=[(1, 'leader'), (0, 'not_leader')])),
                ('clouder', models.IntegerField(choices=[(1, 'clouder'), (0, 'not_clouder')])),
                ('sex', models.IntegerField(choices=[(1, 'male'), (0, 'female')])),
                ('activity', models.IntegerField()),
                ('age', models.IntegerField()),
                ('closeness', models.ManyToManyField(null=True, through='member.Closeness', to='member.Member')),
            ],
        ),
    ]
