# Generated by Django 2.0.3 on 2018-03-18 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TeamBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='closeness',
            name='closeness',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closeness',
            name='friend_from',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='friend_from', to='member.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closeness',
            name='friend_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend_to', to='member.Member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='closeness',
            field=models.ManyToManyField(null=True, related_name='closeness_with', through='member.Closeness', to='member.Member', verbose_name='closeness_with'),
        ),
        migrations.AddField(
            model_name='team',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='member.TeamBase'),
        ),
        migrations.AddField(
            model_name='member',
            name='base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='member.TeamBase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='member.Team'),
            preserve_default=False,
        ),
    ]
