# Generated by Django 2.0.3 on 2018-03-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20180318_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeness',
            name='friend_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeness_to', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='closeness',
            name='friend_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeness_from', to='member.Member'),
        ),
    ]
